# Generated by Django 5.2.17 on 2026-09-13 06:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='稱呼')),
                ('phone', models.CharField(blank=True, max_length=24, verbose_name='電話')),
                ('message', models.TextField(max_length=2000, verbose_name='情況')),
                ('channel', models.CharField(choices=[('telephone', '電話'), ('whatsapp', 'WhatsApp'), ('manual', '其他／手動')], default='manual', max_length=20, verbose_name='來源')),
                ('status', models.CharField(choices=[('new', '待處理'), ('contacted', '已聯絡'), ('qualified', '有效查詢'), ('won', '已成交'), ('closed', '已結束')], default='new', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '查詢紀錄',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='圖片名稱')),
                ('alt', models.CharField(blank=True, max_length=300, verbose_name='預設替代文字')),
                ('file', models.FileField(upload_to='images/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('draft', models.JSONField(default=dict)),
                ('published', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('publish_page', 'Can publish page')],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='快達通渠', max_length=80, verbose_name='網站名稱')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='已確認電話')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='已確認 WhatsApp')),
                ('analytics_enabled', models.BooleanField(default=False, verbose_name='啟用經同意的訪問統計')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '網站設定',
            },
        ),
        migrations.CreateModel(
            name='Throttle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('start', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('target', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hash', models.CharField(db_index=True, max_length=64)),
                ('event', models.CharField(choices=[('page_view', '瀏覽'), ('whatsapp_click', 'WhatsApp 意向'), ('telephone_click', '電話意向')], max_length=24)),
                ('page', models.CharField(max_length=32)),
                ('device', models.CharField(max_length=12)),
                ('environment', models.CharField(default='local', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['environment', 'created_at'], name='cms_event_environ_0e34a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
        ),
    ]
