# Generated by Django 5.2.17 on 2026-09-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_blogcategory_blogtag_integration_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='圖片說明'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='tags',
            field=models.CharField(blank=True, help_text='以逗號分隔，例如：通渠前,高壓水力,商業工程', max_length=300, verbose_name='標籤'),
        ),
    ]
