# Generated by Django 5.2.17 on 2026-09-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_mediaasset_caption_mediaasset_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='telephone',
            field=models.CharField(blank=True, default='85293339580', max_length=20, verbose_name='已確認電話'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, default='85293339580', max_length=20, verbose_name='已確認 WhatsApp'),
        ),
    ]
